# Generated by Django 4.2.2 on 2023-06-29 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Libros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Sin Nombrar', max_length=300, verbose_name='Título del libro')),
                ('edicion', models.CharField(default='Sin Específicar', max_length=300, verbose_name='Edición')),
                ('editorial', models.CharField(default='Sin Específicar', max_length=300, verbose_name='Editorial')),
                ('año_de_publicacion', models.IntegerField(default='Sin Datos', verbose_name='Año de publicación')),
                ('pagina', models.IntegerField(verbose_name='Número de páginas')),
            ],
        ),
    ]
