# Generated by Django 4.2.2 on 2023-07-01 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Productos_Minimos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='N/A', max_length=300, verbose_name='Nombre')),
                ('descripcion', models.CharField(default='N/A', max_length=300, verbose_name='Descripción')),
                ('precio', models.CharField(default='N/A', max_length=300, verbose_name='Precio')),
                ('fecha_registro', models.IntegerField(default=0, verbose_name='Fecha de registro')),
                ('estatus', models.CharField(default='N/A', max_length=300, verbose_name='Estatus')),
            ],
        ),
    ]
