# Generated by Django 4.2.4 on 2023-08-27 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0002_rename_crearreporte_reportes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Responsivas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idd', models.CharField(default='ID del reporte o solicitud...', max_length=300, verbose_name='Título del reporte')),
                ('idd_titulo', models.CharField(default='Asigna el título del reporte o solicitud contestada...', max_length=300, verbose_name='Título del reporte contestado')),
                ('responsiva', models.TextField(default='Escribe aquí la responsiva del problema o solicitud...', max_length=300, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Resposiva',
                'verbose_name_plural': 'Responsiva',
            },
        ),
        migrations.AlterModelOptions(
            name='reportes',
            options={'verbose_name': 'Reportes', 'verbose_name_plural': 'Reportes'},
        ),
        migrations.AlterField(
            model_name='reportes',
            name='accion',
            field=models.CharField(default='Especifica si es reporte o solicitud...', max_length=300, verbose_name='Reportar problema/solicitud de información'),
        ),
        migrations.AlterField(
            model_name='reportes',
            name='categoria',
            field=models.CharField(default='Alumbrado, Civil, Vial o Seguridad...', max_length=300, verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='reportes',
            name='ciudad',
            field=models.CharField(default='Ciudad de donde se genera el reporte...', max_length=300, verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='reportes',
            name='descripcion',
            field=models.TextField(default='Escribe aquí la descripción del problema o solicitud...', max_length=300, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='reportes',
            name='edad',
            field=models.IntegerField(default=0, verbose_name='Edad'),
        ),
        migrations.AlterField(
            model_name='reportes',
            name='estado',
            field=models.CharField(default='Estado de donde se genera el reporte...', max_length=300, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='reportes',
            name='titulo',
            field=models.CharField(default='Asigna un título para tu reporte o solicitud...', max_length=300, verbose_name='Título del reporte'),
        ),
    ]
